spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RACKPAY_KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/rackpay}
  application:
    name: rackpay-api

  datasource:
    url: ${RACKPAY_DATABASE_URL:jdbc:postgresql://localhost:5432/rackpay}
    username: ${RACKPAY_DATABASE_USERNAME:rackpay}
    password: ${RACKPAY_DATABASE_PASSWORD:rackpay}
    hikari:
      maximum-pool-size: ${RACKPAY_DB_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

info:
  app:
    name: RackPay Financial Core
    version: 0.1.0


rackpay:
  keycloak:
    admin:
      base-url: ${RACKPAY_KEYCLOAK_BASE_URL:http://localhost:8081}
      realm: ${RACKPAY_KEYCLOAK_REALM:rackpay}
      client-id: ${RACKPAY_KEYCLOAK_ADMIN_CLIENT_ID:rackpay-admin}
      client-secret: ${RACKPAY_KEYCLOAK_ADMIN_CLIENT_SECRET:}
  wallet:
    default-currency: ${RACKPAY_WALLET_DEFAULT_CURRENCY:EUR}
