package com.rackpay.api.persistence.remittance;
import org.springframework.data.jpa.repository.JpaRepository;
import java.util.Optional;
import java.util.List;
import java.util.UUID;
public interface RemittanceCorridorJpaRepository extends JpaRepository<RemittanceCorridorEntity,UUID>{
 Optional<RemittanceCorridorEntity> findBySourceCountryCodeIgnoreCaseAndDestinationCountryCodeIgnoreCaseAndSourceCurrencyCodeIgnoreCaseAndDestinationCurrencyCodeIgnoreCaseAndEnabledTrue(String sourceCountryCode,String destinationCountryCode,String sourceCurrencyCode,String destinationCurrencyCode);
 List<RemittanceCorridorEntity> findAllBySourceCountryCodeIgnoreCaseAndDestinationCountryCodeIgnoreCaseAndSourceCurrencyCodeIgnoreCaseAndEnabledTrue(String sourceCountryCode,String destinationCountryCode,String sourceCurrencyCode);
}
