import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BadgeCheck, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { apiFetch } from "../../shared/api/httpClient";
import { useAuthStore } from "../../shared/auth/authStore";
import { keycloak } from "../../shared/auth/keycloak";

type Balance={balanceId:string;currency:string;balance:string|number};
type Tx={transactionId:string;operationType:string;amount:string|number;currency:string;status:string;createdAt:string};
type Country={code:string;name:string;dialCode:string;currencyCode:string;receiveEnabled:boolean};
type Network={id:string;code:string;name:string};
const money=(n:string|number,c:string)=>{try{return new Intl.NumberFormat(undefined,{style:"currency",currency:c,maximumFractionDigits:2}).format(Number(n));}catch{return `${n} ${c}`;}};
function Heading({title,description}:{title:string;description:string}){return <div className="page-heading"><div><p className="eyebrow">RACKPAY WORKSPACE</p><h1>{title}</h1><p className="page-description">{description}</p></div></div>;}
function AuthNotice(){return <div className="notice-panel"><ShieldCheck size={22}/><div><strong>Sign in to continue</strong><p>Your financial information is only available in your authenticated session.</p><button className="button button-primary" onClick={()=>void keycloak.login()}>Sign in securely <ArrowRight size={16}/></button></div></div>;}

export function WalletPage(){
 const token=useAuthStore(s=>s.accessToken);const wallet=useQuery({queryKey:["wallet"],queryFn:()=>apiFetch<{balances:Balance[]}>("/api/v1/wallet",{},token),enabled:Boolean(token)});const tx=useQuery({queryKey:["wallet-transactions"],queryFn:()=>apiFetch<{content:Tx[];totalElements:number}>("/api/v1/wallet/transactions?page=0&size=25",{},token),enabled:Boolean(token)});
 const [currency,setCurrency]=useState("EUR");const [message,setMessage]=useState("");const balances=wallet.data?.balances??[];const selected=balances.find(b=>b.currency===currency)??balances[0];
 async function openBalance(){if(!token)return;try{await apiFetch("/api/v1/wallet/balances",{method:"POST",body:JSON.stringify({currency})},token);await wallet.refetch();setMessage(`${currency} balance is ready.`);}catch(e){setMessage(e instanceof Error?e.message:"Unable to open balance.");}}
 return <section><Heading title="Your wallet" description="Manage currency balances and review your account activity."/>{!token?<AuthNotice/>:<>
 <div className="balance-card"><div className="balance-label"><WalletCards size={17}/> Available balance</div>{selected?<><div className="balance-amount">{money(selected.balance,selected.currency)}</div><div className="balance-card-footer"><span>{balances.length} currency balance(s)</span><select value={currency} onChange={e=>setCurrency(e.target.value)} aria-label="Select balance">{balances.map(b=><option key={b.balanceId} value={b.currency}>{b.currency}</option>)}</select></div></>:<><div className="balance-amount">No balances yet</div><p className="balance-subtitle">Open a currency balance to get started.</p></>}
 <div className="balance-open-row"><select value={currency} onChange={e=>setCurrency(e.target.value)} aria-label="Currency to open"><option>EUR</option><option>USD</option><option>GBP</option><option>GHS</option><option>KES</option><option>NGN</option><option>XOF</option><option>UGX</option></select><button className="button button-light" onClick={()=>void openBalance()}>Open balance</button><button className="button button-secondary" onClick={()=>{void wallet.refetch();void tx.refetch();}}>Refresh</button></div></div>
 {message&&<p className="feedback-message" role="status">{message}</p>}<div className="section-heading"><div><h2>Transaction history</h2><p>{tx.data?.totalElements??0} transactions</p></div></div>
 {tx.isLoading?<div className="skeleton-list"/>:tx.isError?<div className="inline-error">Unable to load transactions.<button onClick={()=>void tx.refetch()}>Retry</button></div>:tx.data?.content.length?<div className="transaction-list">{tx.data.content.map(t=><div className="transaction-row" key={t.transactionId}><div className="transaction-icon"><WalletCards size={17}/></div><div className="transaction-info"><strong>{t.operationType.replaceAll("_"," ")}</strong><span>{new Date(t.createdAt).toLocaleString()}</span></div><div className="transaction-value"><strong>{money(t.amount,t.currency)}</strong><span className={`state-pill state-${t.status.toLowerCase()}`}>{t.status.replaceAll("_"," ")}</span></div></div>)}</div>:<div className="empty-state"><strong>No transactions yet</strong><p>Your transactions will appear here.</p><Link className="text-link" to="/remittance">Send money <ArrowRight size={14}/></Link></div>}</>}</section>;
}

export function RemittancePage(){
 const token=useAuthStore(s=>s.accessToken);const [country,setCountry]=useState("");const [network,setNetwork]=useState("");const [phone,setPhone]=useState("");const [sourceCountry,setSourceCountry]=useState("BE");const [currency,setCurrency]=useState("EUR");const [amount,setAmount]=useState("");const [recipient,setRecipient]=useState<{id:string;name?:string;currency:string}|null>(null);const [quote,setQuote]=useState<{quoteId:string;sourceAmount:string;sourceCurrency:string;destinationAmount:string;destinationCurrency:string;feeAmount:string;expiresAt:string}|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const countries=useQuery({queryKey:["remittance-countries"],queryFn:()=>apiFetch<Country[]>("/api/v1/remittances/config/countries?direction=RECEIVE",{},token),enabled:Boolean(token)});const networks=useQuery({queryKey:["remittance-networks",country],queryFn:()=>apiFetch<Network[]>(`/api/v1/remittances/config/countries/${encodeURIComponent(country)}/networks`,{},token),enabled:Boolean(token&&country)});const selected=countries.data?.find(c=>c.code===country);
 async function verify(){if(!token||!selected)return;setBusy(true);setMessage("");setQuote(null);try{const r=await apiFetch<{verified:boolean;recipientId?:string;verifiedName?:string;failureReason?:string}>("/api/v1/remittances/recipients/verify",{method:"POST",body:JSON.stringify({countryCode:country,countryDialCode:selected.dialCode,currency:selected.currencyCode,payoutMethod:"MOBILE_MONEY",networkCode:network,phoneNumber:phone})},token);if(!r.verified||!r.recipientId)throw new Error(r.failureReason||"Recipient could not be verified.");setRecipient({id:r.recipientId,name:r.verifiedName,currency:selected.currencyCode});}catch(e){setMessage(e instanceof Error?e.message:"Recipient verification failed.");}finally{setBusy(false);}}
 async function getQuote(){if(!token||!recipient)return;setBusy(true);setMessage("");try{setQuote(await apiFetch("/api/v1/remittances/quotes",{method:"POST",body:JSON.stringify({recipientId:recipient.id,sourceCountryCode:sourceCountry,sourceCurrency:currency,destinationCurrency:recipient.currency,sourceAmount:amount})},token));}catch(e){setMessage(e instanceof Error?e.message:"Could not create quote.");}finally{setBusy(false);}}
 async function confirm(){if(!token||!quote)return;setBusy(true);setMessage("");try{await apiFetch("/api/v1/remittances/fund",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({quoteId:quote.quoteId})},token);setMessage("Transfer request submitted. Check remittance history for its latest status.");setQuote(null);setRecipient(null);setPhone("");setAmount("");}catch(e){setMessage(e instanceof Error?e.message:"Transfer submission failed.");}finally{setBusy(false);}}
 return <section><Heading title="Send money" description="Verify your recipient, review the quote and confirm your international transfer."/>{!token?<AuthNotice/>:<div className="form-panel">
 <div className="step-heading"><span className="step-number">1</span><div><strong>Recipient details</strong><p>Choose an enabled destination and mobile-money network.</p></div></div>
 <label className="field-label">Destination country</label><select className="form-control" value={country} onChange={e=>{setCountry(e.target.value);setNetwork("");setRecipient(null);setQuote(null);}}><option value="">Select destination</option>{countries.data?.filter(c=>c.receiveEnabled).map(c=><option key={c.code} value={c.code}>{c.name} (+{c.dialCode}) · {c.currencyCode}</option>)}</select>
 <label className="field-label">Mobile-money network</label><select className="form-control" value={network} disabled={!country} onChange={e=>{setNetwork(e.target.value);setRecipient(null);setQuote(null);}}><option value="">Select network</option>{networks.data?.map(n=><option key={n.id} value={n.code}>{n.name}</option>)}</select>
 <label className="field-label">Recipient phone number</label><input className="form-control" autoComplete="tel" inputMode="tel" placeholder="Enter recipient number" value={phone} onChange={e=>{setPhone(e.target.value);setRecipient(null);setQuote(null);}}/>
 <button className="button button-primary full-width" disabled={busy||!country||!network||!phone.trim()} onClick={()=>void verify()}>{busy?"Verifying…":"Verify recipient"} <BadgeCheck size={16}/></button>
 {recipient&&<div className="verified-recipient"><BadgeCheck size={20}/><div><span>Recipient verified</span><strong>{recipient.name||"Verified account holder"}</strong><small>{country} · {network}</small></div></div>}
 {recipient&&<><div className="form-divider"/><div className="step-heading"><span className="step-number">2</span><div><strong>Transfer amount</strong><p>Fees and exchange rate are calculated by the backend.</p></div></div><label className="field-label">Sending country</label><select className="form-control" value={sourceCountry} onChange={e=>setSourceCountry(e.target.value)}><option value="BE">Belgium</option><option value="GH">Ghana</option><option value="KE">Kenya</option><option value="NG">Nigeria</option><option value="UG">Uganda</option></select><div className="amount-input-wrap"><div><label className="field-label">You send</label><input className="amount-input" inputMode="decimal" placeholder="0.00" value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null);}}/></div><select className="currency-select" value={currency} onChange={e=>{setCurrency(e.target.value);setQuote(null);}} aria-label="Source currency"><option>EUR</option><option>USD</option><option>GBP</option><option>GHS</option><option>KES</option><option>NGN</option><option>XOF</option><option>UGX</option></select></div><button className="button button-primary full-width" disabled={busy||!(Number(amount)>0)} onClick={()=>void getQuote()}>{busy?"Calculating…":"Calculate quote"} <ArrowRight size={16}/></button></>}
 {quote&&<div className="quote-card"><p className="eyebrow">TRANSFER SUMMARY</p><div className="quote-line"><span>You send</span><strong>{money(quote.sourceAmount,quote.sourceCurrency)}</strong></div><div className="quote-line"><span>Transfer fee</span><strong>{money(quote.feeAmount,quote.sourceCurrency)}</strong></div><div className="quote-line quote-total"><span>Recipient gets</span><strong>{money(quote.destinationAmount,quote.destinationCurrency)}</strong></div><p className="field-hint">Quote expiry: {new Date(quote.expiresAt).toLocaleTimeString()}.</p><button className="button button-primary full-width" disabled={busy} onClick={()=>void confirm()}>Confirm and submit transfer <ShieldCheck size={16}/></button></div>}
 {message&&<p className="feedback-message" role="status">{message}</p>}<p className="compliance-note"><ShieldCheck size={14}/> RackPay's backend validates the transfer and controls its financial state.</p></div>}</section>;
}
export function TradingPage(){return <section><Heading title="AI Trading" description="Trading activity, investment limits and risk controls."/><div className="notice-panel"><Sparkles size={22}/><div><strong>Trading API integration is pending</strong><p>We won't show simulated balances, positions or returns. Live controls will be connected when the trading API contract is available.</p><span className="feature-tag">Financial safety first</span></div></div><div className="info-grid"><div className="info-tile"><span>Investment limits</span><ShieldCheck size={19}/><strong>Server enforced</strong><p>Limits must be validated by the backend.</p></div><div className="info-tile"><span>Trade history</span><WalletCards size={19}/><strong>Awaiting API</strong><p>Live order history will appear here.</p></div></div></section>;}
export function SettingsPage(){const token=useAuthStore(s=>s.accessToken);return <section><Heading title="Settings" description="Account access and security."/><div className="settings-list"><div className="settings-row"><div><strong>Secure authentication</strong><p>Identity and sessions are managed by Keycloak.</p></div><span className="feature-tag">{token?"Signed in":"Signed out"}</span></div><div className="settings-row"><div><strong>Financial data</strong><p>Balances and transaction states come from the backend.</p></div></div><div className="settings-row"><div><strong>Security reminder</strong><p>Never share passwords or one-time codes with anyone.</p></div></div></div><button className="button button-secondary" onClick={()=>token?void keycloak.logout({redirectUri:window.location.origin}):void keycloak.login()}>{token?"Sign out":"Sign in"}</button></section>;}
